name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - pandas=2.3.3
  - seaborn=0.13.2
  - scikit-learn=1.8.0
  - scipy=1.17.1
  - setuptools=79.0.1
  - pip=26.0.1
  - pip:
      - fg-data-profiling==4.19.1
      - wandb==0.26.0
